### ISSUE TITLE
Broken links in readme / documentation

### ISSUE THREAD

**Issue by scorreard** [sanger-tol/treeval#122]
### Description of the bug

Hi team, 

Amazing work!!

The links in the readme, in the documentation part (usage, parameters and output) give a "page could not be found".

Thanks,

Solenne

**Comment by DLBPointon** [comment]
HI Solenne, 
Thanks for having a look at the project. I have this fixed in a local branch that i'll try and get out as soon as.

**Comment by cabbagesofdoom** [comment]
Hi. This looks like a super-useful workflow. Any chance of posting the updated links to the documentation? Thanks!

**Comment by DLBPointon** [comment]
> Hi. This looks like a super-useful workflow. Any chance of posting the updated links to the documentation? Thanks!

Hi @cabbagesofdoom (fantastic name btw), glad that you think it could be useful! The image corrected documentation can be found here: https://github.com/sanger-tol/treeval/blob/dev/docs/output.md 

I have, however, just noticed that the longread coverage section is lacking it's diagrams. I'll get that fixed.

**Comment by cabbagesofdoom** [comment]
Thanks for the link!

Like the name, buy the book. :P 
http://cabbagesofdoom.blogspot.com/p/cabbages-of-doom.html
