### ISSUE TITLE
REQUEST - R2: HiCat

### ISSUE THREAD

**Issue by DLBPointon** [sanger-tol/treeval#126]
It's been requested that we do at least some preliminary runs with HiCat: https://github.com/xjtu-omics/HiCAT  to compare to internal knowns.

Will require a container as it is only a conda package at the minute.

**Comment by yumisims** [comment]
HiCAT was installed but resulted bug, Kai and students are working on it should have a feedback soon.

**Comment by yumisims** [comment]
HiCat doesn't function denovo centromere identification, not going to be in treeval for now.
