### ISSUE TITLE
REMINDER: Add tutorial documents and scripts

### ISSUE THREAD

**Issue by DLBPointon** [sanger-tol/treeval#138]
I need to add a full work through of how to prep data before running the pipeline.
Synteny, Gene alignment and AEA need classT (make this more clear)
Generalise my prep scripts for this and upload.

Pull gitpod from BGA into repo and upload new test set, data prep step to it.

Anyone else want to add more jobs?

Will not require version update.

**Comment by yumisims** [comment]
make sure we give the credit to Heng's tools.

**Comment by DLBPointon** [comment]
Citations are in the [CITATIONS.md](https://github.com/sanger-tol/treeval/blob/pre-tag/CITATIONS.md). Pretty sure that still covers everything we are using.
