### ISSUE TITLE
Longread Coverage - Convert last column to log2

### ISSUE THREAD

**Issue by weaglesBio** [sanger-tol/treeval#157]
### Description of feature

Last column of coverage.bed file is to be converted to log2. This is to smooth out sharp peaks in coverage plot.
Module will need to be created to process coverage.bed.
Add in just before UCSC_BEDGRAPHTOBIGWIG as punchlists will unmodified version.

Remember to handle log2(0)

**Comment by yumisims** [comment]
if cov ==0 then make cov = 1, so log2(1)=0
