### ISSUE TITLE
minimap2 align with increasing index size 

### ISSUE THREAD

**Issue by yumisims** [sanger-tol/treeval#163]
### Description of feature

potentially would replace the current split-prefix to tackle genome size over 4GB.

**Comment by weaglesBio** [comment]
Yumi's Testing
-I mode
5h 50 min runtime, 45 GB RAM
--split-prefix mode
19h 30 min runtime, 29 GB RAM.
I can see in the log file how the target genome was virtually split into three chunks, each under 4 Gbp, and reads were aligned to each chunk. That’s why it was about 3 times as slow as the -I mod

**Comment by weaglesBio** [comment]
Need to implement in 
- [ ] hic-mapping
- [ ] gene alignment for cds/cdna/rna
