### ISSUE TITLE
mummer optimisation

### ISSUE THREAD

**Issue by yumisims** [sanger-tol/treeval#199]
mummer has limitations (size) on both reference and query sequences. 

(maximum reference length is 2305843009213693948)
(maximum query length is 18446744073709551615)
 
although the above leads to no error warning on input but would lead to huge memory consumption on the mummer step. (Nummer requires approx 30 * reference size RAM to start the job).  To avoid this problem, an additional channel to group reference sequence at max 1G per chunk to result in more efficient performance.

**Comment by DLBPointon** [comment]
```
if ref.size() > 1:
    fasta_ch = [ chunk(fasta) ]
    mummer_chunk_number = ref.chunks * yaml_mummer_chunks
else
    fasta_ch = fasta
```
