### ISSUE TITLE
MerquryFK - segmentation fault on large genomes

### ISSUE THREAD

**Issue by weaglesBio** [sanger-tol/treeval#266]
### Description of the bug

`  .command.sh: line 8:    41 Segmentation fault      MerquryFK -P. -T16 iqMecThal1_T_fk.ktab ref.fa iqMecThal1_T`
On large genome (8.6G assembly)

**Comment by yumisims** [comment]
please check the error rate of the assembly read, if it is too low (below q20), skip this process.

**Comment by yumisims** [comment]
In the future, a feature should be implemented to check if the assembly read type, if it is hifi, then kmer/kmer_coevrage process is included, otherwise, they should be skipped

**Comment by mcshane** [comment]
Note `iqMecThal1` is from HiFi data

**Comment by yumisims** [comment]
nf-core merquery fastk hasn't been updated to the newest bug fixed version, need to use the internal one to make a patch for current module.

**Comment by yumisims** [comment]
fixed
