### ISSUE TITLE
[1.1.1 - Ancient Aurora] - pretextmap, pretextgraph, pretextsnapshot container generation

### ISSUE THREAD

**Issue by yumisims** [sanger-tol/treeval#271]
### Description of feature

Create containers to house the bug-fixed versions of the PretextMap, PretextGraph, and PretextSnapshot. These containers will serve as organised environments where the revised implementations of these components, addressing identified issues, are securely stored and meeting the nf-core software standard.

**Comment by DLBPointon** [comment]
Waiting on new Pretextmap compile to fix memory G error

**Comment by DLBPointon** [comment]
@yumisims Was this ever done or should we close?

**Comment by yumisims** [comment]
all done
