### ISSUE TITLE
FREE UPGRADE - Update tests

### ISSUE THREAD

**Issue by DLBPointon** [sanger-tol/treeval#287]
### Description of feature

GitHub has doubled the resources available to public and opensource projects
https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

We can use 4 core and 16Gb

**Comment by DLBPointon** [comment]
Merged in #288 , above error was not related.

**Comment by DLBPointon** [comment]
Hi @muffato, tagging you in case you haven't seen the news

**Comment by muffato** [comment]
I didn't know ! It's great 🕺🏼 
Can you please send a message to #pipelines tomorrow ?
