### ISSUE TITLE
Clean up repository

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#35]
### Description of feature

@DLBPointon mentioned there might be some outdated modules, can you please remove these? Remove any modules or subworkflows no longer necessary. Remove commented out pieces of code, if not part of testing.

When you create a PR for this, please reference this issue, and set `dev` as the base branch.

**Comment by DLBPointon** [comment]
Currently removing redundant modules. No redundant workflows. As far as I can tell no more commented-out code, what is left is a boilerplate for Phase 2's coverage sub-workflow. 

Commited in next round of updates.

**Comment by DLBPointon** [comment]
New local module scripts are now in bin cae1652ddd5802b598f7bee6fa54bb31ae9cd5a9

**Comment by priyanka-surana** [comment]
It might be best not to nest `bin` directory, keep a flat structure. It sometimes throws an error, that the script is not found. You can always name it `tool_subtool.ext` to preserve all the information.

**Comment by muffato** [comment]
@DLBPointon You removed a bunch of modules in #51 . Can this issue be considered as addressed ?

**Comment by DLBPointon** [comment]
I think so at this point. I've removed a number of outdated modules and added documentation (in the form of SUB-WORKFLOW, MODULE, and LOGIC explainers) throughout the pipeline.
