### ISSUE TITLE
Modules restructuring

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#36]
This is a summary issue, please create PRs for the individual issues referenced here.

1. #37 The structure of the modules is incorrect. Take a look at [genomenote](https://github.com/sanger-tol/genomenote/tree/dev/modules) for the structure expected. You may need to delete the entire contents below [`modules/nf-core`](https://github.com/sanger-tol/treeval/tree/main/modules/nf-core) and repopulate using `nf-core modules install`.
2. #38 The [`miniprot`](https://github.com/sanger-tol/treeval/tree/main/modules/sanger-tol/nf-core-modules/miniprot) modules need to first be submitted to `nf-core` using released [bioconda](https://bioconda.github.io/recipes/miniprot/README.html) package and containers. Then install under `nf-core` using `nf-core modules install`.
3. #39 There is already a combined [`minimap2` + `samtools` module](https://github.com/nf-core/modules/blob/master/modules/nf-core/minimap2/align/main.nf) in nf-core. Please use that instead of [`minimap_samtools`](https://github.com/sanger-tol/treeval/blob/main/modules/local/minimap_samtools.nf)
4. #40 `samtools` in [`merge_bam`](https://github.com/sanger-tol/treeval/blob/main/modules/local/merge_bam.nf) module will not work without a container in production env. There is already a module for [samtools merge](https://github.com/nf-core/modules/blob/master/modules/nf-core/samtools/merge/main.nf), please use that instead.
5. #41 There is already a combined [`bamToBed` + `bedtools sort` module](https://github.com/nf-core/modules/blob/master/modules/nf-core/bedtools/bamtobed/main.nf) in nf-core. Please use that instead of [`bedtools_bed_sort`](https://github.com/sanger-tol/treeval/blob/main/modules/local/bedtools_bed_sort.nf). You also have a redundant module under [`sanger-tol`](https://github.com/sanger-tol/treeval/blob/main/modules/sanger-tol/nf-core-modules/bedtools/bamtobed/main.nf). Only keep one copy under `nf-core`.
6. #42 The [`blast/tblastn`](https://github.com/sanger-tol/treeval/tree/main/modules/sanger-tol/nf-core-modules/blast/tblastn) needs to be removed from `sanger-tol` and installed under `nf-core`. If not using, remove entirely.
7. #43 For the modules under [`makecmap`](https://github.com/sanger-tol/treeval/tree/main/modules/sanger-tol/nf-core-modules/makecmap), please move the scripts with the credits and licence information intact to the `bin` folder. Then, use a `perl` conda package and containers to create local modules using `nf-core modules create` from within the pipeline. If you make any changes to the original scripts, please address these in the script header, so credit is given where due. Do the same for [`selfcomp/splitfasta`](https://github.com/sanger-tol/treeval/blob/main/modules/sanger-tol/nf-core-modules/selfcomp/splitfasta/main.nf).
8. #44 For the modules [`selfcomp/mapids`](https://github.com/sanger-tol/treeval/blob/main/modules/sanger-tol/nf-core-modules/selfcomp/mapids/main.nf) and [`selfcomp/mummer2bed`](https://github.com/sanger-tol/treeval/blob/main/modules/sanger-tol/nf-core-modules/selfcomp/mummer2bed/main.nf) do the same as N°7 but with a python package and container.
9. #45 For these local modules, please add a bioconda package and container. You can use a basic one: https://github.com/nf-core/modules/blob/master/modules/nf-core/md5sum/main.nf 
- [`get_synteny_genomes`](https://github.com/sanger-tol/treeval/blob/main/modules/local/get_synteny_genomes.nf)
- [`generate_genome_file`](https://github.com/sanger-tol/treeval/blob/main/modules/local/generate_genome_file.nf)
- [`csv_generator`](https://github.com/sanger-tol/treeval/blob/main/modules/local/csv_generator.nf)
- [`concatmummer`](https://github.com/sanger-tol/treeval/blob/main/modules/local/concatmummer.nf) (only conda needs adding)
- [`concat_gff`](https://github.com/sanger-tol/treeval/blob/main/modules/local/concat_gff.nf)
- [`chunkfasta`](https://github.com/sanger-tol/treeval/blob/main/modules/local/chunkfasta.nf) ([pyfasta conda package](https://bioconda.github.io/recipes/pyfasta/README.html) exists)
- [`cat_blast`](https://github.com/sanger-tol/treeval/blob/main/modules/local/cat_blast.nf)
- [`bb_generator`](https://github.com/sanger-tol/treeval/blob/main/modules/local/bb_generator.nf)
10. #47 For local module [`filter_blast`](https://github.com/sanger-tol/treeval/blob/main/modules/local/filter_blast.nf), add the script in your bin folder (which seems to be missing) and use the appropriate conda package and containers as needed. Please do not package the script in a container. 
11. #46 For the different `cat` local modules, might be better to use a generic one and configure it for different purposes as needed – see [nf-core cat module](https://github.com/nf-core/modules/blob/master/modules/nf-core/cat/cat/main.nf). Example: [`concatmummer`](https://github.com/sanger-tol/treeval/blob/main/modules/local/concatmummer.nf), [`concat_gff`](https://github.com/sanger-tol/treeval/blob/main/modules/local/concat_gff.nf) and [`cat_blast`](https://github.com/sanger-tol/treeval/blob/main/modules/local/cat_blast.nf)
12. It is best to create local modules using `nf-core modules create` from within the pipeline directory. The idea is to keep the formatting and structure of the local modules as close to the nf-core ones.
13. Before creating any bespoke containers, please have a chat. There are [multi-package containers](https://github.com/BioContainers/multi-package-containers) and other options available, which would save you time and make your pipeline more reproducible.

@muffato is happy to help with tasks above so please contact him if you need help.
@priyanka-surana is happy to help manage this release, we can have regular catch ups to keep track of the work.

**Comment by yumisims** [comment]
We refurbished the pipeline by replacing most reliable tools in the pipeline recently for the gene annotion, I think we should have done some clean up before merging the workflow. 

As for point 1, and 2 have you documented the rule somewhere we could check up, because I am confused why what module to submit to nf-core what to sanger nf-core.

I suggest we will make pull request when the pipeline stable.

Thank you for your effort.

**Comment by muffato** [comment]
I think this ticket needs a bit more explanation. The review aggregates all the issues that we've raised already in other discussions, and is motivated by:
1. making the pipeline usable in our production environment (currently not possible because of 4)
2. reducing the amount of code you / we need to maintain (2, 3, 5, 6, 11)
3. allowing to exchange modules and code with others, incl. from ToLA (currently not possible because of 1 – nf-core pushed that breaking change, not us)
4. reducing the barrier to entry for other people (incl. from ToLA ) to contribute and debug, by following the same structure (1, 12, and 13)
5. making the pipeline inspectable / modifiable by non-Sanger people (currently not possible because of 7, 8, 10)
6. making the pipeline usable outside of our production environment (currently at risk because of 9)

I'm happy to start making pull-requests now to show how it can be done, so that your own pull-requests can abide by the same rules.

**Comment by muffato** [comment]
I would also recommend to move away from `bedtools sort` if you can. It's less efficient than a regular `sort`, as the bedtools authors say themselves (see the disclaimer at the bottom of https://bedtools.readthedocs.io/en/latest/content/tools/sort.html) and it's indeed caused us some problems in the read-mapping pipeline.

**Comment by priyanka-surana** [comment]
I am breaking these down into individual issues so that you can work on them individually, we will leave this issue as a summary. Sorry for the multiple notifications.

As for what should be under `nf-core` vs `local` vs `sanger-tol`, based on the modules I have reviewed so far, I don't believe anything here needs to be under `sanger-tol`. In general, any public tool with no special licence restrictions (ex: longranger), can be under `nf-core`. If you are using personal scripts or similar, add them under `local`. I reserve `sanger-tol` for special licence software (longranger) or public software that we have modified for ToL wide use (ex: arima). If you have questions, please send them to me here or on Slack.

**Comment by DLBPointon** [comment]
I believe this can be closed now too, these points have been completed in the past two rounds of fixes.
