### ISSUE TITLE
Restructure modules folder

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#37]
### Description of the bug

The structure of the modules is incorrect. Take a look at [genomenote](https://github.com/sanger-tol/genomenote/tree/dev/modules) for the structure expected. You may need to delete the entire contents below [modules/nf-core](https://github.com/sanger-tol/treeval/tree/main/modules/nf-core) and repopulate using `nf-core modules install`.

From Matthieu:
> motivated by allowing to exchange modules and code with others, incl. from ToLA (currently not possible – nf-core pushed that breaking change, not us)
> motivated by reducing the barrier to entry for other people (incl. from ToLA ) to contribute and debug, by following the same structure

**Comment by DLBPointon** [comment]
Reorganised, Will be fixed in the next round of updates.

Although, these have been installed incorrectly by nf-core. Removing and re-installing resulted in the same error in the structure.

**Comment by priyanka-surana** [comment]
You mentioned on Slack that using `nf-core tools v2.6` fixed the structure. Is it good? Or are you still having issues?

**Comment by DLBPointon** [comment]
Using 2.6 has fixed the structure yes, however, i'm no longer able to make use of the `--git-remote` flag.

**Comment by priyanka-surana** [comment]
That is on us. `sanger-tol/nf-core-modules` stopped pulling from `nf-core/modules` when the big restructuring happened. Since we stopped updating, I think the structure mismatch prevents the use with the updates `tools` version. But we had to since the `sanger-tol` modules would otherwise have been removed. 

Anyway, for `treeval` since there are no `sanger-tol` modules you are using, that should be okay. I think `genomeassembly` is the only one using it. `miniprot` is on `nf-core` as well now. But if you need something from `sanger-tol`, add it as local for now.

We are working on an updated `sanger-tol` modules repository with all the existing Sanger specific modules transferred.
