### ISSUE TITLE
miniprot module to nf-core

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#38]
### Description of feature

The [miniprot](https://github.com/sanger-tol/treeval/tree/main/modules/sanger-tol/nf-core-modules/miniprot) modules need to first be submitted to nf-core using released [bioconda](https://bioconda.github.io/recipes/miniprot/README.html) package and containers. Then install under nf-core using `nf-core modules install`.

From Matthieu:
> motivated by reducing the amount of code you / we need to maintain

**Comment by muffato** [comment]
nf-core pull-request: https://github.com/nf-core/modules/pull/2627
