### ISSUE TITLE
Use nf-core minimap2

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#39]
### Description of feature

There is already a combined [minimap2 + samtools module](https://github.com/nf-core/modules/blob/master/modules/nf-core/minimap2/align/main.nf) in nf-core. Please use that instead of [minimap_samtools](https://github.com/sanger-tol/treeval/blob/main/modules/local/minimap_samtools.nf)

From Matthieu:
>  motivated by reducing the amount of code you / we need to maintain

**Comment by DLBPointon** [comment]
We are already using the nf-core module, the minimap_samtools module is a dead remnant from testing. Removing in the next round of updates.
