### ISSUE TITLE
Samtools merge container missing

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#40]
### Description of the bug

Samtools in [merge_bam](https://github.com/sanger-tol/treeval/blob/main/modules/local/merge_bam.nf) module will not work without a container in production env. There is already a module for [samtools merge](https://github.com/nf-core/modules/blob/master/modules/nf-core/samtools/merge/main.nf), please use that instead.

From Matthieu:
> motivated by making the pipeline usable in our production environment (currently not possible)

**Comment by DLBPointon** [comment]
This is already in use, the one you are referring to is a test module. Removing with next round of updates.
