### ISSUE TITLE
Use nf-core bamToBed

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#41]
### Description of feature

There is already a combined [bamToBed + bedtools sort module](https://github.com/nf-core/modules/blob/master/modules/nf-core/bedtools/bamtobed/main.nf) in nf-core. Please use that instead of [bedtools_bed_sort](https://github.com/sanger-tol/treeval/blob/main/modules/local/bedtools_bed_sort.nf). You also have a redundant module under [sanger-tol](https://github.com/sanger-tol/treeval/blob/main/modules/sanger-tol/nf-core-modules/bedtools/bamtobed/main.nf). Only keep one copy under nf-core.

From Matthieu:
> motivated by reducing the amount of code you / we need to maintain
> 
> I would also recommend to move away from bedtools sort if you can. It's less efficient than a regular sort, as the bedtools authors say themselves (see the disclaimer at the bottom of https://bedtools.readthedocs.io/en/latest/content/tools/sort.html) and it's indeed caused us some problems in the read-mapping pipeline.

More details on the issue with `bedtools sort`: https://github.com/sanger-tol/genomenote/issues/51

If you do separate the `sort`, please make sure it is a different module. You can borrow this [`gnu_sort`](https://github.com/sanger-tol/genomenote/blob/dev/modules/local/gnu_sort.nf) module.

**Comment by DLBPointon** [comment]
bamToBed + sort is already in use. Sort was being run after this, again, so that has been removed. Redundancy removed.

We will have a look at moving to gnu_sort once the fixes are in.
