### ISSUE TITLE
Use nf-core blastn

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#42]
### Description of feature

The [blast/tblastn](https://github.com/sanger-tol/treeval/tree/main/modules/sanger-tol/nf-core-modules/blast/tblastn) needs to be removed from sanger-tol and installed under nf-core. If not using, remove entirely.

From Matthieu:
> motivated by reducing the amount of code you / we need to maintain

**Comment by DLBPointon** [comment]
BLAST* is no longer used, will be removed in the next round of updates.
