### ISSUE TITLE
Create local modules for `makecmap` and `splitfasta`

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#43]
### Description of feature

For the modules under [makecmap](https://github.com/sanger-tol/treeval/tree/main/modules/sanger-tol/nf-core-modules/makecmap), please move the scripts with the credits and licence information intact to the bin folder. Then, use a perl conda package and containers to create local modules using nf-core modules create from within the pipeline. If you make any changes to the original scripts, please address these in the script header, so credit is given where due. Do the same for [selfcomp/splitfasta](https://github.com/sanger-tol/treeval/blob/main/modules/sanger-tol/nf-core-modules/selfcomp/splitfasta/main.nf).

From Matthieu:
> motivated by making the pipeline inspectable / modifiable by non-Sanger people (currently not possible)

**Comment by DLBPointon** [comment]
Scripts are now included as of cae1652ddd5802b598f7bee6fa54bb31ae9cd5a9
