### ISSUE TITLE
Create local modules for `selfcomp`

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#44]
### Description of feature

For the modules [selfcomp/mapids](https://github.com/sanger-tol/treeval/blob/main/modules/sanger-tol/nf-core-modules/selfcomp/mapids/main.nf) and [selfcomp/mummer2bed](https://github.com/sanger-tol/treeval/blob/main/modules/sanger-tol/nf-core-modules/selfcomp/mummer2bed/main.nf) please move the scripts with the credits and licence information intact to the bin folder. Then, use a python conda package and containers to create local modules using `nf-core modules create` from within the pipeline. If you make any changes to the original scripts, please address these in the script header, so credit is given where due.

From Matthieu:
> motivated by making the pipeline inspectable / modifiable by non-Sanger people (currently not possible

**Comment by DLBPointon** [comment]
Scripts are now included as of cae1652ddd5802b598f7bee6fa54bb31ae9cd5a9

**Comment by weaglesBio** [comment]
Changes merged into dev branch.
