### ISSUE TITLE
Add containers and conda package to local modules

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#45]
### Description of the bug

For these local modules, please add a bioconda package and container. You can use a basic one: https://github.com/nf-core/modules/blob/master/modules/nf-core/md5sum/main.nf
* [get_synteny_genomes](https://github.com/sanger-tol/treeval/blob/main/modules/local/get_synteny_genomes.nf)
* [generate_genome_file](https://github.com/sanger-tol/treeval/blob/main/modules/local/generate_genome_file.nf)
* [csv_generator](https://github.com/sanger-tol/treeval/blob/main/modules/local/csv_generator.nf)
* [concatmummer](https://github.com/sanger-tol/treeval/blob/main/modules/local/concatmummer.nf) (only conda needs adding)
* [concat_gff](https://github.com/sanger-tol/treeval/blob/main/modules/local/concat_gff.nf)
* [chunkfasta](https://github.com/sanger-tol/treeval/blob/main/modules/local/chunkfasta.nf) ([pyfasta conda package](https://bioconda.github.io/recipes/pyfasta/README.html) exists)
* [cat_blast](https://github.com/sanger-tol/treeval/blob/main/modules/local/cat_blast.nf)
* [bb_generator](https://github.com/sanger-tol/treeval/blob/main/modules/local/bb_generator.nf)

From Matthieu:
> motivated by making the pipeline usable outside of our production environment (currently at risk)

**Comment by weaglesBio** [comment]
The following will not be updated as the are being removed in the next update as part of issue #46:
- [concatmummer](https://github.com/sanger-tol/treeval/blob/main/modules/local/concatmummer.nf) (only conda needs adding)
- [concat_gff](https://github.com/sanger-tol/treeval/blob/main/modules/local/concat_gff.nf)
- [cat_blast](https://github.com/sanger-tol/treeval/blob/main/modules/local/cat_blast.nf)

**Comment by weaglesBio** [comment]
[bb_generator](https://github.com/sanger-tol/treeval/blob/main/modules/local/bb_generator.nf)[bb_generator](https://github.com/sanger-tol/treeval/blob/main/modules/local/bb_generator.nf) is deprecated so will be removed.

**Comment by weaglesBio** [comment]
ECLint errors will be resolved as part of other issues.
