### ISSUE TITLE
Module `filter_blast` change container

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/treeval#47]
### Description of feature

For local module [`filter_blast`](https://github.com/sanger-tol/treeval/blob/main/modules/local/filter_blast.nf), add the script in your bin folder (which seems to be missing) and use the appropriate conda package and containers as needed. Please do not package the script in a container. 

From Matthieu:
> motivated by making the pipeline inspectable / modifiable by non-Sanger people (currently not possible)

**Comment by DLBPointon** [comment]
This will be removed in the next update. Filter_blast is a Phase 1 remnant, replaced with minimap2 and miniprot.
