### ISSUE TITLE
Make the CI tests pass on GitHub

### ISSUE THREAD

**Issue by muffato** [sanger-tol/treeval#53]
### Description of feature

(as per https://github.com/sanger-tol/treeval/pull/51#issuecomment-1397191162 )

Currently, the integration tests only pass on the farm, because some config paths refer to `/nfs/team135` (at least the one I've found, perhaps some are on `/lustre` too). It would be useful to update the S3 test profile to include _all_ data on the S3 server. This way, reviewers could rely on GitHub to test pull-requests and wouldn't need to run the pipeline themselves.

This would also tell us / confirm what the pipeline needs from the Sanger infrastructure, and allow to plan the next steps for the pipeline being usable by external collaborators, for when we feel ready to support that.

**Comment by DLBPointon** [comment]
CI on GitHub works now as of d68fea56f1274818515660829eb669f955d6e9ab
