### ISSUE TITLE
Generate parameters.md

### ISSUE THREAD

**Issue by weaglesBio** [sanger-tol/treeval#54]
### Description of feature

1. _nextflow_schema.json_ needs to be updated to reflect current parameters.

~2. `nf-core schema docs -x markdown` to generate prettified version of this schema. Save as parameters.md in the docs folder.~

~Based on documentation guidance [here](https://github.com/sanger-tol/nf-core-pipeline/wiki/8.-Documentation)~

**Comment by priyanka-surana** [comment]
That documentation is old and archived. The latest version does not need `parameters.md`. You can skip that, but do update the `nextflow_schema.json` as this will also be used by the scheduler.
