### ISSUE TITLE
Add _prot to gene alignment peptide output

### ISSUE THREAD

**Issue by weaglesBio** [sanger-tol/treeval#77]
### Description of feature

Add _prot to end of gene alignment peptide file names (.gff.gz). To be consistent with the cds, cdna and rna.

**Comment by DLBPointon** [comment]
I've added this in minor_fixes [a9e10a9](https://github.com/sanger-tol/treeval/commit/a9e10a9e2479baa48a6d77341d83d79708bbe1b7)
